# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabTartExecutor < Formula
  desc "GitLab Runner Executor to run jobs inside isolated Tart VMs"
  homepage "https://github.com/marcusfreisleben/gitlab-tart-executor"
  version "1.0.3"

  depends_on "cirruslabs/cli/tart"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/marcusfreisleben/gitlab-tart-executor/releases/download/v1.0.3/gitlab-tart-executor-darwin-arm64.tar.gz"
    sha256 "4b669019250bcfb0689ed8153e58bea6d50141986c49331395b48e598a43c4f0"

    def install
      bin.install "gitlab-tart-executor"
    end
  end

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end
end
